version: '2.1'

services:

  db:
    image: cockroachdb/cockroach:v1.1.4
    command: start --insecure
    ports:
      - 8080:8080
      - 26257:26257
    volumes:
      - ./data/cockroach-data:/cockroach/cockroach-data
    restart: always
    network_mode: bridge

  init:
     image: cockroachdb/cockroach:v1.1.4
     volumes:
       - ./dev/setup_db.sh:/setup_db.sh
       - ./dev/backup.sql:/dev/backup.sql
     entrypoint: "/bin/bash"
     command: /setup_db.sh
     links:
       - db
     network_mode: bridge
