[log]
level = "INFO"

[crdb]
database = "triton"
host = "127.0.0.1"
port = 26257
password = ""
user = "root"

[agent]
log-format = "auto"

[http]
bind = "127.0.0.1"
port = 3000
dc = "us-east-1"

[gops]
enable = true
bind = "127.0.0.1"
port = 9191

[pprof]
enable = true
bind = "127.0.0.1"
port = 9090

[nomad]
url = "127.0.0.1"
port = 4646

[triton]
dc = "us-east-1"
url = "https://us-east-1.api.joyent.com"
