[log]
level = "INFO"

[postgresql]
database = "triton"
host = "127.0.0.1"
port = 26257
password = ""
user = "root"

[run]
log-format = "auto"

[http]
bind = "127.0.0.1"
port = 3000

[gops]
enable = true
bind = "127.0.0.1"
port = 9191

[pprof]
enable = true
bind = "127.0.0.1"
port = 9090
